image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

cache:
  paths:
    - .m2/repository

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

validate:
  stage: validate
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS validate'
  except:
    - tags

compile:
  stage: validate
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS clean compile'
  except:
    - tags

check-style:
  stage: validate
  script:
    - 'rm -rf target/site'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS checkstyle:checkstyle'
  except:
    - tags
  artifacts:
    paths:
      - target/site/checkstyle.html
    expire_in: 4 days

unit-test:
  stage: test
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS test'
  except:
    - tags

integration-test:
  stage: test
  script:
    - 'wget http://cache.1gps.com.br/mavenhelper.jar'
    - 'java -jar mavenhelper.jar it `find . -type f -name IntegrationTest.java`'
    - 'rm -f pom.xml'
    - 'mv output.xml pom.xml'
    - 'mvn $MAVEN_CLI_OPTS failsafe:integration-test'
  tags:
    - docker
  except:
    - tags
coverage:
  stage: test
  script:
    - 'wget http://cache.1gps.com.br/mavenhelper.jar'
    - 'java -jar mavenhelper.jar it `find . -type f -name IntegrationTest.java`'
    - 'rm -f pom.xml'
    - 'mv output.xml pom.xml'
    - 'java -jar mavenhelper.jar cc'
    - 'rm -f pom.xml'
    - 'mv output.xml pom.xml'
    - 'mvn $MAVEN_CLI_OPTS verify -P all-tests'
    - 'cat target/site/jacoco/index.html'
  tags:
    - docker
  except:
    - tags
qualitygate:
  stage: test
  script:
    - 'wget http://cache.1gps.com.br/mavenhelper.jar'
    - 'java -jar mavenhelper.jar it `find . -type f -name IntegrationTest.java`'
    - 'rm -f pom.xml'
    - 'mv output.xml pom.xml'
    - 'java -jar mavenhelper.jar cc'
    - 'rm -f pom.xml'
    - 'mv output.xml pom.xml'
    - 'java -jar mavenhelper.jar cs'
    - 'mvn $MAVEN_CLI_OPTS versions:set -DnewVersion="$PROJ_MAIN_VER.$PROJ_SUB_VER.$CI_PIPELINE_ID"'
    - 'mvn $MAVEN_CLI_OPTS versions:commit'
    - 'mvn $MAVEN_CLI_OPTS package'
    - 'mvn $MAVEN_CLI_OPTS sonar:sonar --settings .m2/settings.xml'
  tags:
    - docker
  except:
    - tags

build:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS package'
  only:
    - master
  except:
    - tags
  tags:
    - docker

artifactory:
  stage: artifact
  script:
    - 'wget http://cache.1gps.com.br/mavenhelper.jar'
    - 'java -jar mavenhelper.jar cs'
    - 'java -jar mavenhelper.jar artifactory $CI_COMMIT_SHA $CI_PROJECT_URL $CI_SERVER_VERSION'
    - 'rm -f pom.xml'
    - 'mv output.xml pom.xml'
    - 'mvn $MAVEN_CLI_OPTS versions:set -DnewVersion="$PROJ_MAIN_VER.$PROJ_SUB_VER.$CI_PIPELINE_ID"'
    - 'mvn $MAVEN_CLI_OPTS versions:commit'
    - 'mvn $MAVEN_CLI_OPTS javadoc:jar deploy -D maven.test.skip=true --settings .m2/settings.xml'
  only:
    - master
  except:
    - tags
  image: maven:3.3.9-jdk-8
  tags:
    - docker
tagging:
  stage: artifact
  script:
    - 'curl -X POST http://mportaldesenv.dynalias.com:8088/api/v4/projects/$CI_PROJECT_ID/repository/tags -H "content-type: application/json" -H "private-token: $APITOKEN" -d "{ \"id\": $CI_PROJECT_ID, \"tag_name\": \"v$PROJ_MAIN_VER.$PROJ_SUB_VER.$CI_PIPELINE_ID\", \"ref\": \"$CI_COMMIT_SHA\", \"release_description\": \"Generated By GitLab\", \"message\": \"Generated By GitLab\" }"'
  only:
    - master
  except:
    - tags

deploy-prd-brasil:
  stage: deploy
  when: manual
  environment:
    name: prd-brasil
    url: tcp://177.8.165.18:6501
  before_script:
    - yum install epel-release -y
    - yum install sshpass -y
  script:
    - sshpass -p "$SSHPASSWORD" ssh -o StrictHostKeyChecking=no root@50.0.0.10 "wget http://mportaldesenv.dynalias.com:8081/artifactory/libs-release-local/br/com/multiportal/gateway/${PROJ_MAIN_VER}.${PROJ_SUB_VER}.${CI_PIPELINE_ID}/gateway-${PROJ_MAIN_VER}.${PROJ_SUB_VER}.${CI_PIPELINE_ID}.jar -O /home/gtw/gatewayv3/gatewayv3.jar"
    - sshpass -p "$SSHPASSWORD" ssh -o StrictHostKeyChecking=no root@50.0.0.10 "/home/gtw/gatewayv3/init.sh"
  tags:
    - docker
  only:
    - master
  except:
    - tags

deploy-prd-comunitarios:
  stage: deploy
  when: manual
  environment:
    name: prd-comunitarios-us
    url: tcp://173.224.125.30:6501
  before_script:
    - yum install epel-release -y
    - yum install sshpass -y
  script:
    - sshpass -p "$SSHPASSWORD" ssh -o StrictHostKeyChecking=no root@69.64.56.152 -p300 "wget http://mportaldesenv.dynalias.com:8081/artifactory/libs-release-local/br/com/multiportal/gateway/${PROJ_MAIN_VER}.${PROJ_SUB_VER}.${CI_PIPELINE_ID}/gateway-${PROJ_MAIN_VER}.${PROJ_SUB_VER}.${CI_PIPELINE_ID}.jar -O /home/gtw/gatewayv3.jar"
    - sshpass -p "$SSHPASSWORD" ssh -o StrictHostKeyChecking=no root@69.64.56.152 -p300 "/home/gtw/finishg3.sh"
  tags:
    - docker
  only:
    - master
  except:
    - tags

deploy-prd-tesb:
  stage: deploy
  when: manual
  environment:
    name: prd-tesb
    url: tcp://69.64.56.185:6501
  before_script:
    - yum install epel-release -y
    - yum install sshpass -y
  script:
    - sshpass -p "$SSHPASSWORD" ssh -o StrictHostKeyChecking=no root@69.64.56.185 -p300 "wget http://mportaldesenv.dynalias.com:8081/artifactory/libs-release-local/br/com/multiportal/gateway/${PROJ_MAIN_VER}.${PROJ_SUB_VER}.${CI_PIPELINE_ID}/gateway-${PROJ_MAIN_VER}.${PROJ_SUB_VER}.${CI_PIPELINE_ID}.jar -O /home/gtw/gatewayv3/gatewayv3.jar"
    - sshpass -p "$SSHPASSWORD" ssh -o StrictHostKeyChecking=no root@69.64.56.185 -p300 "/home/gtw/gatewayv3/init.sh"
  tags:
    - docker
  only:
    - master
  except:
    - tags