image: maven:3.3.9-jdk-8

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true"
  MAVEN_CLI_OPTS: "-s .m2/settings.xml --batch-mode --errors --fail-at-end --show-version -DdmUser=$MAVEN_REPO_USER -DdmPass=$MAVEN_REPO_PASS"

cache:
  paths:
    - .m2/repository

stages:
  - validate
  - test
  - build
  - artifact
  - deploy

validate:
  stage: validate
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS validate'
  except:
    - tags

compile:
  stage: validate
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS clean compile'
  except:
    - tags

check-style:
  stage: validate
  script:
    - 'rm -rf target/site'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS checkstyle:checkstyle'
  except:
    - tags
  artifacts:
    paths:
      - target/site/checkstyle.html
    expire_in: 4 days

build:
  stage: build
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS package'
  only:
    - master
  except:
    - tags

artifactory:
  stage: artifact
  script:
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS versions:set -DnewVersion="$CI_COMMIT_REF_NAME"'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS versions:commit'
    - 'mvn $MAVEN_OPTS $MAVEN_CLI_OPTS javadoc:jar javadoc:javadoc: source:jar deploy '
  only:
    - tags